FROM node:16-alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY package* ./

RUN npm install

RUN npm install -g --unsafe-perm serve

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

COPY . .

RUN npm run build

CMD ["serve", "-s", "-l", "5000", "build"]

