version: '3.8'

services:

    reverse-proxy:
      image: nginx:1.21.6-alpine
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      container_name: nginx

    db:
      image: postgres:14.3-alpine
      container_name: postgres-db
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./data:/var/lib/postgresql/data

    redis-service:
      image: redis:7.0.0-alpine
      container_name: redis

    example-backend:
      image: bshr/example-backend
      command: ./server
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres-db
      container_name: example-backend
      depends_on:
        - db


    example-frontend:
      image: bshr/example-frontend
      command: ["serve", "-s", "-l", "5000", "build"]
      build: ./example-frontend
      ports:
        - 5000:5000
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080/
      container_name: example-frontend
