version: '3.8'

services:

    example-backend:
      image: bshr/example-backend
      command: ./server
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
      container_name: example-backend


    example-frontend:
      image: bshr/example-frontend
      command: ["serve", "-s", "-l", "5000", "build"]
      build: ./example-frontend
      ports:
        - 5000:5000
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080/
      container_name: example-frontend
